services:
  - type: web
    name: youtube-audio-proxy
    env: node
    plan: free
    buildCommand: "apt-get update && apt-get install -y ffmpeg python3-pip && pip3 install -U yt-dlp && npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1 