services:
  - type: web
    name: youtube-audio-proxy
    env: node
    plan: free
    buildCommand: "apt-get update && apt-get install -y wget ffmpeg && wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp && npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1 